### PR TITLE
re-correct HYB-GROUP-BITS

### PR DESCRIPTION
**Pull request by infradom**
Dont know when this was introduced
I believed I corrected this, but the error re-appeared

### CODE REVIEW

**Comment by wills106** [comment]
Looks like I messed up and reintroduced it on this commit https://github.com/wills106/homsassistant-solax-modbus/commit/c14e15c079abe6954e87e114b05f6b0ca29796eb

**Comment by wills106** [comment]
Just hope I haven't messed up and re-introduced any other errors?

**Comment by infradom** [comment]
We will see ..  I can check when I find some time

**Comment by wills106** [comment]
I need to get better at making sure my installation matches Github, before I make any changes locally before I push them back out.

**Comment by infradom** [comment]
It can indeed be confusing working with many levels. I experience the same:
     local copy <> my github fork <>  your main line

On first sight, I did not find any other changes that got lost, but I only verified a couple of things.

**Pull request merged**
