### PR TITLE
Corrections to resolve issue reported byu @mickemartinsson 

### PR DESCRIPTION
**Pull request by infradom**
Corrections to resolve issue reported byu @mickemartinsson 
Added total battery energy input and output also

### CODE REVIEW

**Comment by infradom** [comment]
you may need to remove the first line of the readme file if you merge this

**Comment by wills106** [comment]
Is it possible for me to just merge 2d2253c as we don't really need the readme commit?

Not sure if I can just merge half of a PR?

If not I'll just edit the readme after

**Comment by infradom** [comment]
not sure, I am not a git expert.
I should have removed that first line myself before the PR

**Comment by wills106** [comment]
Think I managed to approve just the last bit?

**Comment by wills106** [comment]
O I think I reverted the README.md on your branch 🤦‍♂️ as well

**Pull request merged**
